apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    k8s-app: etcd
  name: etcd-discovery
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 2379
    protocol: TCP
    targetPort: 2379
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: etcd
    k8s-app: etcd
  name: etcd-discovery
  namespace: kube-system
subsets:
- addresses:
  {% for master in groups['master'] %}
- ip: {{ hostvars[master].ansible_host }}
  {% endfor %}
ports:
  - name: https
    port: 2379
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    interval: 30s
    port: https
    relabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  jobLabel: etcd
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: etcd

