---
- name: restart docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
- name: restart kube-proxy
  systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
