---
- name: install python-apt on ubuntu 16.04
  apt:
   name: "{{item.src}}"
   state: present
   update_cache: yes
  with_items:
  - { src: "python-apt" }
- name: Gather the  package facts
  package_facts:
    manager: auto
- name: remove package on ubuntu 16.04
  apt:
   name: "{{item.src}}"
   state: absent
  with_items:
  - { src: "docker" }
  - { src: "docker-engine" }
  - { src: "docker.io" }
  - { src: "containerd" }
  - { src: "runc" }
  when:
  - item.src in ansible_facts.packages
- name: install package on ubuntu 16.04
  apt:
   name: "{{item.src}}"
   state: present
   update_cache: yes
  with_items:
  - { src: "apt-transport-https" }
  - { src: "ca-certificates" }
  - { src: "curl" }
  - { src: "gnupg-agent" }
  - { src: "software-properties-common" }
  - { src: "ipset" }
  when:
  - item.src not in ansible_facts.packages
- name: add repository key on ubuntu 16.04
  apt_key:
   url: https://download.docker.com/linux/ubuntu/gpg
   state: present
- name: add repository on ubuntu 16.04
  apt_repository:
   repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
- name: install docker package on ubuntu 16.04
  apt:
   name: "{{item.src}}"
   state: present
   update_cache: yes
  with_items:
  - { src: "docker-ce=5:18.09.9~3-0~ubuntu-xenial" }
  - { src: "docker-ce-cli=5:18.09.9~3-0~ubuntu-xenial" }
  - { src: "containerd.io" }
  when:
  - item.src.split("=")[0] not in ansible_facts.packages
- name: copy docker config file
  copy:
   src: daemon.json
   dest: /etc/docker/daemon.json
  notify:
  - "restart docker daemon"
- name: wait for docker config file
  wait_for:
   path: /etc/docker/daemon.json
   state: present
- name: start docker daemon
  systemd:
   name: docker
   state: started
   enabled: yes
   daemon_reload: yes
- name: wait for docker started
  wait_for:
   path: /var/run/docker.sock
   state: present
  
