---
#- name: set hosts
#  lineinfile:
#    path: /etc/hosts
#    regexp: '^127\.0\.0\.1'
#    line: '127.0.0.1 {{inventory_hostname}}'
#    owner: root
#    group: root
#    mode: 0644

#- name: set hostname
#  hostname:
#   name: "{{inventory_hostname}}"
- include: install-docker-centos.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7"
- include: install-docker-ubuntu.yml
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version == "16"

