---
- name: firewalld setting
  hosts: mongocluster
  roles:
   - {role: firewalld}
- name: sysctl setting
  hosts: all
  roles:
   - {role: sysctl}
- name: mongo replication
  hosts: mongocluster
  roles:
   - {role: mongodb}
