---
- name: manage sysctl 
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.conf
  with_items:
    - { name: "vm.swappiness",value: "0"}
    - { name: "net.ipv4.neigh.default.gc_stale_time",value: "120"}
    - { name: "net.ipv4.conf.all.rp_filter",value: "0"}
    - { name: "net.ipv4.conf.default.rp_filter",value: "0"}
    - { name: "net.ipv4.conf.default.arp_announce",value: "2"}
    - { name: "net.ipv4.conf.lo.arp_announce",value: "2"}
    - { name: "net.ipv4.conf.all.arp_announce",value: "2"}
    - { name: "net.ipv4.tcp_max_tw_buckets",value: "5000"}
    - { name: "net.ipv4.tcp_syncookies",value: "1"}
    - { name: "net.ipv4.tcp_max_syn_backlog",value: "8192"}
    - { name: "net.ipv4.tcp_syncookies",value: "1"}
    - { name: "net.ipv4.tcp_synack_retries",value: "2"}
    - { name: "net.ipv4.tcp_syn_retries",value: "1"}
    - { name: "net.ipv4.ip_forward",value: "0"}
    - { name: "net.ipv4.conf.default.accept_source_route",value: "0"}
    - { name: "kernel.sysrq",value: "0"}
    - { name: "kernel.core_uses_pid",value: "1"}
    - { name: "kernel.msgmnb",value: "65536"}
    - { name: "kernel.msgmax",value: "65536"}
    - { name: "kernel.shmmax",value: "68719476736"}
    - { name: "kernel.shmall",value: "4294967296"}
    - { name: "net.ipv4.tcp_sack",value: "1"}
    - { name: "net.ipv4.tcp_window_scaling",value: "1"}
    - { name: "net.ipv4.tcp_rmem",value: "4096        87380    4194304"}
    - { name: "net.ipv4.tcp_wmem",value: "4096        16384    4194304"}
    - { name: "net.core.wmem_default",value: "8388608"}
    - { name: "net.core.wmem_max",value: "16777216"}
    - { name: "net.core.rmem_default",value: "8388608"}
    - { name: "net.core.rmem_max",value: "16777216"}
    - { name: "net.core.netdev_max_backlog",value: "262144"}
    - { name: "net.core.somaxconn",value: "2048"}
    - { name: "net.ipv4.tcp_max_orphans",value: "3276800"}
    - { name: "net.ipv4.tcp_timestamps",value: "0"}
    - { name: "net.ipv4.tcp_tw_recycle",value: "1"}
    - { name: "net.ipv4.tcp_tw_reuse",value: "1"}
    - { name: "net.ipv4.tcp_mem",value: "94500000 915000000 927000000"}
    - { name: "net.ipv4.tcp_fin_timeout",value: "1"}
    - { name: "net.ipv4.tcp_keepalive_time",value: "30"}
    - { name: "net.ipv4.ip_local_port_range",value: "1024    65000"}
    - { name: "fs.file-max",value: "102400"}
