---
- include: setup_install.yml
- include: setup-startup_CentOS-7.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
- include: setup-startup_CentOS6-or-Ubuntu14.04.yml
  when: ( ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6' )
         or ( ansible_os_family == 'Debian' )
