---
- name: install package on RedHat
  yum:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ install_with_package }}"
  when: ansible_os_family == 'RedHat'

- name: install package on Ubuntu
  apt:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ install_with_package_ubuntu }}"
  when: ansible_os_family == 'Debian'
