---
- name: issue some package stop and disabled on CentOS6 or ubuntu 14.04
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - "{{ disabled_package_on_C6_U14 }}"
  ignore_errors: true
- name: template file to remote hosts
  template:
    src: ssh.local.j2
    dest: /etc/fail2ban/jail.d/ssh.local
  notify:
    - service restart fail2ban
- name:  start fail2ban
  service:
    name:  fail2ban
    state: started
    enabled: yes
