---
- name: remove the docker package on CentOS
  yum:
    name: "{{item}}"
    state: absent
  with_items:
  - docker
  - docker-client
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate 
  - docker-engine
- name: add yum-utils package on CentOS
  yum:
   name: "{{item}}"
   state: present
   update_cache: yes
  with_items:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  - curl
- name: add repository on CentOS
  yum_repository:
   baseurl: "https://download.docker.com/linux/centos/docker-ce.repo"
   state: present
   enabled: yes
   gpgcheck: no
- name: install docker 1809 on CentOS
  yum:
   name: "{{item}}"
   state: present
   update_cache: yes
  with_items:
  - docker-ce-18.09
  - docker-ce-cli-18.09
  - containerd.io
