---
- name: unarchive file to remote hosts CentOS 7
  unarchive:
   src: mongodb-linux-x86_64-rhel70-3.4.4.tar
   dest: /usr/local/
   creates: /usr/local/mongodb-linux-x86_64-rhel70-3.4.4
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
- name: links files on CentOS 7
  file:
   src: /usr/local/mongodb-linux-x86_64-rhel70-3.4.4
   dest: /usr/local/mongodb
   state: link
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
- name: unarchive file to remote hosts Ubuntu 14.04
  unarchive:
   src: mongodb-linux-x86_64-ubuntu1404-3.4.4.tar
   dest: /usr/local/
   creates: /usr/local/mongodb-linux-x86_64-ubuntu1404-3.4.4
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version == '14'
- name: links files on Ubuntu 14.04
  file:
   src: /usr/local/mongodb-linux-x86_64-ubuntu1404-3.4.4
   dest: /usr/local/mongodb
   state: link
  when: ansible_os_family == 'Debian' and ansible_distribution_major_version == '14'
- name: unarchive file to remote hosts CentOS 6
  unarchive:
   src: mongodb-linux-x86_64-rhel62-3.4.4.tar
   dest: /usr/local/
   creates: /usr/local/mongodb-linux-x86_64-rhel62-3.4.4
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
- name: links files  on CentOS 6
  file:
   src: /usr/local/mongodb-linux-x86_64-rhel62-3.4.4
   dest: /usr/local/mongodb
   state: link
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
