---
- name: download cfssl binary file
  get_url:
    url: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0744
  with_items:
  - { src: "https://pkg.cfssl.org/R1.2/cfssl_linux-amd64", dest: "/usr/local/bin/cfssl"}
  - { src: "https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64", dest: "/usr/local/bin/cfssljson"}
  - { src: "https://pkg.cfssl.org/R1.2/cfssl-certinfo_linux-amd64", dest: "/usr/local/bin/cfssl-certinfo"}
