---
- name: translate cfssl binary files
  become: yes
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: 0755
  with_items:
  - { src: "cfssl_linux-amd64", dest: "/usr/local/bin/cfssl"}
  - { src: "cfssljson_linux-amd64", dest: "/usr/local/bin/cfssljson"}
  - { src: "cfssl-certinfo_linux-amd64", dest: "/usr/local/bin/cfssl-certinfo"}
