---
- name: set default INPUT ACCEPT
  iptables:
   chain: INPUT
   policy: ACCEPT
   state: present
  when: ansible_os_family == 'RedHat'   and ansible_distribution_major_version == '6'
- name: flush CentOS 6 iptables
  iptables:
   flush: yes
   chain: INPUT
  when: ansible_os_family == 'RedHat'   and ansible_distribution_major_version == '6'
- name: setting customize iptables rule
  iptables:
   chain: INPUT
   destination_port: "{{ item.port }}"
   state: present
   ctstate: NEW
   source: "{{ item.source }}"
   jump: ACCEPT
   protocol: tcp
  with_items:
   - "{{ firewall_open_port }}"
- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    state: present
- name: set default INPUT DROP 
  iptables:
   chain: INPUT
   policy: DROP
   state: present
