---
- include: setup-firewall.yml
  when: ansible_os_family == 'RedHat'   and ansible_distribution_major_version == '7'
- include: setup-iptables.yml
  when:  ( ansible_os_family == 'RedHat'  and  ansible_distribution_major_version == '6' )  
         or ( ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04' )   
         
